# Generated by Django 4.2.7 on 2023-12-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('equipment', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('computer_name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('vendor', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('assigned', models.BooleanField(default=True)),
            ],
        ),
    ]
