# Generated by Django 4.2.7 on 2023-12-29 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventorydb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='tag_number',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_type', models.CharField(choices=[('POST', 'POST'), ('PATCH', 'PATCH'), ('PUT', 'PUT')], max_length=10)),
                ('changes_made', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(blank=True, max_length=100, null=True)),
                ('retrieved_from', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('subsidiary', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('location', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('remark', models.CharField(default=None, max_length=100, null=True)),
                ('action_type', models.CharField(blank=True, max_length=20, null=True)),
                ('date_retrieved', models.DateField(blank=True, null=True)),
                ('tag_number_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventorydb.inventory')),
            ],
        ),
    ]
