# Generated by Django 4.2.7 on 2023-12-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventorydb", "0002_inventory_serial_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
