# Generated by Django 4.2.7 on 2023-12-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventorydb", "0002_alter_inventory_tag_number_apilog_actionlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),

    ]
