# Generated by Django 4.2.7 on 2023-12-01 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventorydb", "0003_alter_inventory_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventory", old_name="date_added", new_name="created_at",
        ),
    ]
