# Generated by Django 4.2.7 on 2024-01-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorydb', '0003_inventory_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10),
        ),
    ]
