# Generated by Django 4.2.7 on 2023-12-01 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventorydb", "0004_rename_date_added_inventory_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 1, 14, 17, 49, 318171),
                editable=False,
            ),
        ),
    ]
